version: '3.2'

services:
  backend:
    image: onion
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app:delegated
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - notused:/opt/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: mysql:5.6.42
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test-db
      MYSQL_USER: root
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  notused:
  mysql_data: