version: '3.2'

services:
  backend:
    image: onion
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app:delegated
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - notused:/opt/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend_network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6.42
    ports:
      - 3100:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: DATABASE_NAME
      MYSQL_USER: DATABASE_USERNAME
      MYSQL_PASSWORD: DATABASE_PASSWORD
      MYSQL_ROOT_PASSWORD: DATABASE_PASSWORD
    networks:
      - backend_network

volumes:
  notused:
  mysql_data:

networks:
  backend_network:
