version: '3.2'

services:
  backend:
    image: onion
    ports:
      - 3000:3000
    volumes:
    - .:/opt/app:delegated
    - ./package.json:/opt/package.json
    - ./yarn.lock:/opt/yarn.lock
    - notused:/opt/app/node_modules
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  notused: